// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuMV_YtY2YEN4Au8hvYjdPLoIi9CiPkUA',
    appId: '1:212280973944:web:a0493030841a7f6e31eb8d',
    messagingSenderId: '212280973944',
    projectId: 'pharmacy-management-b244e',
    authDomain: 'pharmacy-management-b244e.firebaseapp.com',
    storageBucket: 'pharmacy-management-b244e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfgORzgO__UhoeCDX4l-PVWlfSIDpAdvM',
    appId: '1:489901287674:android:2c1928205bc51f168d8143',
    messagingSenderId: '489901287674',
    projectId: 'pharmacy-managment-6e7d4',
    storageBucket: 'pharmacy-managment-6e7d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLICb-86mKNU6-VHUkegFnnGhoPAzmoFI',
    appId: '1:212280973944:ios:1e8581016a1d462831eb8d',
    messagingSenderId: '212280973944',
    projectId: 'pharmacy-management-b244e',
    storageBucket: 'pharmacy-management-b244e.firebasestorage.app',
    iosBundleId: 'com.example.mypharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLICb-86mKNU6-VHUkegFnnGhoPAzmoFI',
    appId: '1:212280973944:ios:1e8581016a1d462831eb8d',
    messagingSenderId: '212280973944',
    projectId: 'pharmacy-management-b244e',
    storageBucket: 'pharmacy-management-b244e.firebasestorage.app',
    iosBundleId: 'com.example.mypharmacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuMV_YtY2YEN4Au8hvYjdPLoIi9CiPkUA',
    appId: '1:212280973944:web:b1ab6f374734419e31eb8d',
    messagingSenderId: '212280973944',
    projectId: 'pharmacy-management-b244e',
    authDomain: 'pharmacy-management-b244e.firebaseapp.com',
    storageBucket: 'pharmacy-management-b244e.firebasestorage.app',
  );
}